### PR TITLE
Add rotation for levers

### PR DESCRIPTION
**Pull request by Svarr**
This PR adds the rotation values for levers (as per the `lever_direction` block state property), only. It does not add support for the `open_bit` property (i.e. activation state of the lever).

### CODE REVIEW

**Comment by RavinMaddHatter** [comment]
This looks okay. I know it would be hacky, but you could change the model of the "on" and "off" as variants and define it in then block shapes and "nbt_def"  i need to test. It will take some time as i have a really big refactor local that i am working on...

**Comment by Svarr** [comment]
> This looks okay. I know it would be hacky, but you could change the model of the "on" and "off" as variants and define it in then block shapes and "nbt_def" i need to test. It will take some time as i have a really big refactor local that i am working on...

The problem is, that there are two parts to the shape, which both have to be rotated differently. As I have outlined in #153, I chose to allow for the definition of rotations right in `block_shapes` for each part of the geometry individually. These would have to be applied in addition to the rotation defined in `block_rotation`. But this approach seems to exhaust the limits of euler angles (i.e. _gimbal lock_).

Anyway, until you are done with the refactoring there isn't much sense in continuing working on this, as I don't know which of the changes I make will still be relevant in the end.

**Comment by RavinMaddHatter** [comment]
The refactor is in the layer above this. So I haven't changed anything in
the actual block code. If there is a recommendation on how to change the
block code I can look at that.

Euler angles are a place I am admittedly weak. Do you have any suggestions
on how I would change this in general, I want to avoid changes that are
block specific if possible. But just how you would describe a block
genetically would help.

**Comment by Svarr** [comment]
I answered in the [corresponding ticket](https://github.com/RavinMaddHatter/Structura/issues/153#issuecomment-1408499850), as this PR is centered on providing the block rotations, so that the lever appears attached to the correct block in the schematic.

Although, considering that they will be changed again within the scope of #153, a merge wouldn't be sensible unless you plan on making a release before #153 is resolved.

**Comment by Svarr** [comment]
I'm closing this PR in favour of a new one that I'm going to create soon (see https://github.com/RavinMaddHatter/Structura/issues/153#issuecomment-1423958942).

**Pull request closed without merging**
