### PR TITLE
1.5.3 update!

### PR DESCRIPTION
**Pull request by Wulian233**
Modify the font and position of the debug text
Some tkinter use tkinter.ttk
Some words are capitalized

### CODE REVIEW

**Comment by RavinMaddHatter** [comment]
I am not sure if the dependency on SV_ttk will break android support. I am trying to move to Kivy but i have not got that fully working yet.

I am not sure if i want to take this in the main file as it is unclear if it will break android... even though i dont support it, functionally adding a new library is not really helping that effort.

**Comment by Wulian233** [comment]
> Python can support Android?I don't know how this is done.However, one theme may support it.（I'm not sure.）

**Comment by RavinMaddHatter** [comment]
There is a python interpreter for Android.

**Comment by Wulian233** [comment]
I revised pr again and deleted sv-ttk module. I think it can be merged this time. thank you!

**Comment by Wulian233** [comment]
I revised pr again and deleted sv-ttk module. I think it can be merged this time. thank you!

**Pull request closed without merging**
