### PR TITLE
Block definition fix

### PR DESCRIPTION
**Pull request by TetianaLitvinova**
- Fixed color variations for concrete and shulker boxes;
- Fixed missing support for gray carpet;
- Removed a few duplicate lines in files;
- Fixed some spelling errors.

### CODE REVIEW

**Comment by RavinMaddHatter** [comment]
One thing is that i think this breaks old structures. IE if you grab an old structure file it will now be broken. I try and not remove support for old blocks if i can.

**Comment by TetianaLitvinova** [comment]
I've returned what I removed (and even added some missing old definitions, not sure if it's needed) and kept new one's. 
I also added new names and definitions that has been added in the recent updates (stained glass, stained glass panes, terracotta and concrete powder). But adding them unfortunately didn't make them to show in the pack.
Only clear glass and glass panes work at this point.

I am fairly new to Minecraft packs, so I am not sure what else needs an update to make them work.

**Review by RavinMaddHatter — APPROVED** [review]
Looks good

**Comment by RavinMaddHatter** [comment]
This is now deployed to the update function. and to the bot in my discord. Thanks for the PR

**Pull request merged**
